# Generated by Django 5.2.3 on 2025-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identity_number',
            field=models.CharField(default='0000000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
